import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { createMockServices } from '../src/services/mock/createMockServices.js';
import { ADMINISTRATOR_ACCOUNT } from '../src/services/mock/seedData.js';
import { PERMISSIONS, permissionsForRole, friendlyServiceError, ServiceError } from '../src/services/contracts.js';

const memory = new Map();
const services = createMockServices({ storage: { getItem: key => memory.get(key) ?? null, setItem: (key, value) => memory.set(key, String(value)), removeItem: key => memory.delete(key) } });
await services.initialize();
await services.auth.signIn({ email: ADMINISTRATOR_ACCOUNT.email, password: ADMINISTRATOR_ACCOUNT.password });
const overview = await services.administration.getOverview();
const target = overview.users.find(user => user.role === 'planning');
assert.ok(target);
const reason = 'Fabricated automatic role permission validation';
const verification = ADMINISTRATOR_ACCOUNT.password;
const roles = values => services.administration.assignAccountRoles(target.id, { roles: values, reason, verification });
const permissions = values => services.administration.setAccountPermissions(target.id, { permissions: values, reason, verification });
let changed = await roles(['planning', 'dispatch']);
const defaults = [...new Set([...permissionsForRole('planning'), ...permissionsForRole('dispatch')])];
assert.deepEqual([...changed.permissions].sort(), [...defaults].sort());
changed = await roles(['dispatch']);
assert.ok(!changed.permissions.includes(PERMISSIONS.VIEW_PLANNING_QUEUE));
assert.ok(changed.permissions.includes(PERMISSIONS.VIEW_DISPATCH_QUEUE));
assert.ok(changed.permissions.includes(PERMISSIONS.READ_CATALOGUE));
changed = await roles(['planning', 'dispatch']);
changed = await permissions([...changed.permissions.filter(code => code !== PERMISSIONS.CONFIRM_DELIVERY), PERMISSIONS.VIEW_TECHNICAL_QUEUE]);
assert.ok(!changed.permissions.includes(PERMISSIONS.CONFIRM_DELIVERY));
assert.ok(changed.permissions.includes(PERMISSIONS.VIEW_TECHNICAL_QUEUE));
changed = await roles(['dispatch']);
assert.ok(!changed.permissions.includes(PERMISSIONS.VIEW_PLANNING_QUEUE));
assert.ok(!changed.permissions.includes(PERMISSIONS.CONFIRM_DELIVERY));
assert.ok(changed.permissions.includes(PERMISSIONS.VIEW_TECHNICAL_QUEUE));
changed = await permissions(permissionsForRole('dispatch'));
assert.deepEqual([...changed.permissions].sort(), [...permissionsForRole('dispatch')].sort());
const refreshed = (await services.administration.getOverview()).users.find(user => user.id === target.id);
assert.deepEqual([...refreshed.permissions].sort(), [...changed.permissions].sort());
assert.deepEqual(refreshed.deniedPermissions, []);
assert.deepEqual(refreshed.additionalPermissions, []);
await assert.rejects(roles(['administrator']));
await assert.rejects(permissions([PERMISSIONS.ADMINISTER_USERS]));

const ui = await fs.readFile(new URL('../src/components/AdministratorDashboard.jsx', import.meta.url), 'utf8');
assert.match(ui, /AdministrationDialog error={error}/);
assert.match(ui, /overview.permissions \|\| \[\]/, 'permission selector must use service-provided catalogue');
assert.match(ui, /Reset to assigned role defaults/);
assert.match(ui, /role default/);
assert.match(friendlyServiceError(new ServiceError('Private detail', { code: 'ADMIN_VERIFICATION_FAILED', status: 403 })), /password confirmation failed/);
console.log('Role inheritance, additive roles, removal, explicit exceptions, protected permissions and dialog feedback passed.');
