const step = ({
  id,
  label,
  customerLabel,
  description,
  sequence,
  requiredForDispatch = false,
  selectableForUpdate = true,
  operational = false,
  terminal = false,
}) => Object.freeze({
  id,
  label,
  customerLabel,
  description,
  sequence,
  requiredForDispatch,
  selectableForUpdate,
  operational,
  terminal,
});

export const EXPEDITOR_PROGRESS_STEPS = Object.freeze([
  step({
    id: 'planning_received',
    label: 'Planning received',
    customerLabel: 'Planning received',
    description: 'The planned order has been accepted into the Expediting queue.',
    sequence: 10,
    requiredForDispatch: true,
    selectableForUpdate: false,
  }),
  step({
    id: 'materials_checked',
    label: 'Materials checked',
    customerLabel: 'Materials checked',
    description: 'Material availability and requirements have been checked.',
    sequence: 20,
    requiredForDispatch: true,
  }),
  step({
    id: 'materials_ordered',
    label: 'Materials ordered',
    customerLabel: 'Materials ordered',
    description: 'Required materials have been ordered.',
    sequence: 30,
  }),
  step({
    id: 'awaiting_materials',
    label: 'Awaiting materials',
    customerLabel: 'Awaiting materials',
    description: 'The order is waiting for required materials.',
    sequence: 40,
  }),
  step({
    id: 'materials_received',
    label: 'Materials received',
    customerLabel: 'Materials received',
    description: 'Required materials have been received.',
    sequence: 50,
  }),
  step({
    id: 'production_started',
    label: 'Production started',
    customerLabel: 'Production started',
    description: 'Production or fulfilment work has started.',
    sequence: 60,
    requiredForDispatch: true,
  }),
  step({
    id: 'assembly_in_progress',
    label: 'Assembly in progress',
    customerLabel: 'Assembly in progress',
    description: 'Assembly is currently in progress.',
    sequence: 70,
  }),
  step({
    id: 'calibration_or_testing',
    label: 'Calibration or testing',
    customerLabel: 'Calibration or testing',
    description: 'Calibration or functional testing is in progress.',
    sequence: 80,
    requiredForDispatch: true,
  }),
  step({
    id: 'quality_check',
    label: 'Quality check',
    customerLabel: 'Quality check',
    description: 'The order is undergoing its quality review.',
    sequence: 90,
    requiredForDispatch: true,
  }),
  step({
    id: 'paperwork_preparation',
    label: 'Paperwork preparation',
    customerLabel: 'Paperwork preparation',
    description: 'The required dispatch paperwork is being prepared.',
    sequence: 100,
    requiredForDispatch: true,
  }),
  step({
    id: 'ready_for_dispatch',
    label: 'Ready for dispatch',
    customerLabel: 'Ready for dispatch',
    description: 'The order is ready to be handed to Dispatch.',
    sequence: 110,
    requiredForDispatch: true,
  }),
  step({
    id: 'on_hold',
    label: 'On hold',
    customerLabel: 'On hold',
    description: 'Work is paused while information, approval or materials are awaited.',
    sequence: 900,
    selectableForUpdate: false,
    operational: true,
  }),
  step({
    id: 'cancelled',
    label: 'Cancelled',
    customerLabel: 'Cancelled',
    description: 'The order was cancelled through the controlled management workflow.',
    sequence: 999,
    selectableForUpdate: false,
    operational: true,
    terminal: true,
  }),
]);

export const EXPEDITOR_PROGRESS_STEP_IDS = Object.freeze(EXPEDITOR_PROGRESS_STEPS.map(item => item.id));
export const REQUIRED_EXPEDITOR_STEP_IDS = Object.freeze(
  EXPEDITOR_PROGRESS_STEPS.filter(item => item.requiredForDispatch).map(item => item.id),
);

export const EXPEDITOR_DOCUMENT_TYPES = Object.freeze([
  { id: 'document', label: 'Document reference' },
  { id: 'image', label: 'Image reference' },
  { id: 'quality_record', label: 'Quality record' },
  { id: 'other', label: 'Other controlled reference' },
]);
