import { requirePermission } from '../authorization/permissions.js';
import { validationError } from '../errors.js';

const defaults=()=>({schemaVersion:1,setupCompleted:false,themePreset:'rhomberg-default',fontSize:'medium',density:'standard',appearanceMode:'light',notificationPreferences:{rfqUpdates:true,quotationNotifications:true,orderProgress:true,delayNotifications:true,fulfilmentNotifications:true,accountSecurity:true,maintenanceNotices:true,companyAnnouncements:true},profileImage:null,updatedAt:''});
const choices={themePreset:new Set(['rhomberg-default']),fontSize:new Set(['small','medium','large','extra-large']),density:new Set(['comfortable','standard','compact']),appearanceMode:new Set(['light','dark','system'])};
const ensureCustomer=actor=>{if(!actor.roles?.includes('customer')){const error=new Error('Customer personalisation is available only in Rhomberg Connect.');error.code='FORBIDDEN';error.statusCode=403;throw error;}};

export function createPersonalisationService({repository,storage}) {
  const get=async actor=>{ensureCustomer(actor);const row=await repository.getUserSettings(actor);return {...defaults(),...(row?.settings?.personalisation||{}),notificationPreferences:{...defaults().notificationPreferences,...(row?.settings?.personalisation?.notificationPreferences||{})},updatedAt:row?.updated_at||''};};
  const save=async(actor,input)=>{ensureCustomer(actor);const errors={};for(const [key,set] of Object.entries(choices))if(!set.has(input?.[key]))errors[key]=`Choose a recognised ${key}.`;if(Object.keys(errors).length)throw validationError(errors);const current=await repository.getUserSettings(actor);const value={...defaults(),...input,companyLogo:null,updatedAt:new Date().toISOString()};await repository.saveUserSettings(actor,{...(current?.settings||{}),personalisation:value});await repository.saveNotificationPreferences(actor,{categories:value.notificationPreferences});return value;};
  return Object.freeze({get,save,async reset(actor,input){const current=defaults();current.setupCompleted=!Boolean(input?.reopenSetup);return save(actor,current);},async uploadImage(actor,file,position,correlationId){ensureCustomer(actor);if(!file)throw validationError({image:'Choose a profile image.'});const document=await storage.put(file);try{const image=await repository.saveUserProfileImage(actor,actor.id,document,correlationId);if(image.previousStorageKey)await storage.remove(image.previousStorageKey).catch(()=>undefined);const current=await get(actor);const profileImage={id:actor.id,previewUrl:`/api/v1/users/me/personalisation/images/${actor.id}`,position:{x:Number(position?.x)||50,y:Number(position?.y)||50}};await save(actor,{...current,profileImage});return profileImage;}catch(error){await storage.remove(document.storageKey).catch(()=>undefined);throw error;}},async removeImage(actor,id,correlationId){ensureCustomer(actor);if(id!==actor.id)requirePermission(actor,'administer_users');const removed=await repository.removeUserProfileImage(actor,actor.id,correlationId);if(removed.storageKey)await storage.remove(removed.storageKey).catch(()=>undefined);const current=await get(actor);await save(actor,{...current,profileImage:null});return {removed:true};},async image(actor){ensureCustomer(actor);const image=await repository.getUserProfileImage(actor,actor.id);return {...image,buffer:await storage.get(image.storage_key||image.storageKey)};}});
}
