import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { accountCan, friendlyServiceError, PERMISSIONS, USER_ROLES } from '../services/contracts.js';
import { ConfiguredUnitDetails } from './ConfiguredUnitDetails.jsx';
import { MockAdministrationControls } from './MockAdministrationControls.jsx';
import { StatusBadge } from './StatusBadge.jsx';

const humanise = value => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase());
const emptyDialog = () => ({ mode: '', target: null, values: {}, reason: '', verification: '' });
const today = () => new Date().toISOString().slice(0, 10);
const blankEmployee = () => ({ firstName: '', surname: '', displayName: '', email: '', username: '', password: '', branchId: '', department: '', primaryRole: '', additionalRoles: [], authenticationType: 'password', activationMethod: 'verified_email_invitation', profileImage: null });
const blankCustomer = () => ({ companyName: '', contactName: '', email: '', phone: '', area: '', industry: '', branchId: '', representativeId: '', password: '' });

export function AdministratorDashboard({ account, administrationActions, serviceMode, onOpenManagement, onOpenAudit, onOpenArchive, onRecordsChanged }) {
  const [overview, setOverview] = useState(null);
  const [tab, setTab] = useState('overview');
  const [query, setQuery] = useState('');
  const [filters, setFilters] = useState({ status: 'all', branch: 'all', department: 'all', role: 'all' });
  const [busy, setBusy] = useState('');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [dialog, setDialog] = useState(emptyDialog);
  const [oneTimeCredential, setOneTimeCredential] = useState(null);

  const load = async () => {
    setError('');
    try { setOverview(await administrationActions.getOverview()); }
    catch (loadError) { setError(friendlyServiceError(loadError, 'Administration data could not be loaded.')); }
  };
  useEffect(() => { load(); }, [account.id]);

  const run = async (key, operation, success, onSuccess) => {
    setBusy(key); setError(''); setMessage('');
    try {
      const result = await operation();
      await load();
      await onRecordsChanged?.();
      setDialog(emptyDialog());
      setMessage(success);
      onSuccess?.(result);
      return result;
    } catch (runError) { setError(friendlyServiceError(runError, 'The administrator action could not be completed.')); }
    finally { setBusy(''); }
    return null;
  };

  const filteredUsers = useMemo(() => {
    const term = query.trim().toLowerCase();
    return (overview?.users || []).filter(user => (
      (filters.status === 'all' || user.status === filters.status)
      && (filters.branch === 'all' || user.branchId === filters.branch)
      && (filters.department === 'all' || user.department === filters.department)
      && (filters['role'] === 'all' || (user.roles || [user.role]).includes(filters['role']))
      && (!term || [user.contact, user.email, user.signInName, user.company, user.department, ...(user.roles || [user.role])].some(value => String(value || '').toLowerCase().includes(term)))
    ));
  }, [overview, query, filters]);

  const openEmployee = () => setDialog({ mode: 'employee', target: null, values: blankEmployee(), reason: '', verification: '' });
  const openCustomer = () => setDialog({ mode: 'customer', target: null, values: blankCustomer(), reason: '', verification: '' });
  const openUser = user => setDialog({ mode: 'user', target: user, values: { contact: user.contact, email: user.email || '', signInName: user.signInName || '', phone: user.phone || '', area: user.area || '', branchId: user.branchId || '', department: user.department || '', profileImage: null }, reason: '', verification: '' });
  const openRoles = user => setDialog({ mode: 'roles', target: user, values: { roles: [...(user.roles || [user.role])] }, reason: '', verification: '' });
  const openBranch = user => setDialog({ mode: 'branch', target: user, values: { branchId: user.branchId || '', effectiveDate: today() }, reason: '', verification: '' });
  const openReset = user => setDialog({ mode: 'reset', target: user, values: {}, reason: '', verification: '' });
  const openProfile = user => setDialog({ mode: 'profile', target: user, values: { profileImage: null }, reason: '', verification: '' });
  const openArchive = user => setDialog({ mode: 'archive', target: user, values: { lastWorkingDate: today(), replacementEmployeeId: '' }, reason: '', verification: '' });
  const openHistory = async user => {
    setBusy(`history-${user.id}`); setError('');
    try {
      const [audit, logins] = await Promise.all([administrationActions.getUserAudit(user.id), administrationActions.getUserLoginHistory(user.id)]);
      setDialog({ mode: 'history', target: user, values: { audit, logins }, reason: '', verification: '' });
    } catch (historyError) { setError(friendlyServiceError(historyError, 'User history could not be loaded.')); }
    finally { setBusy(''); }
  };
  const openCompany = company => setDialog({ mode: 'company', target: company, values: { name: company.name, area: company.area, industry: company.industry, branchId: company.branchId || '' }, reason: '', verification: '' });
  const openRepresentative = company => setDialog({ mode: 'representative', target: company, values: { representativeId: company.representativeId || '' }, reason: '', verification: '' });
  const openPermissions = user => setDialog({ mode: 'permissions', target: user, values: { permissions: [...(user.permissions || [])] }, reason: '', verification: '' });
  const openNotifications = user => setDialog({ mode: 'notifications', target: user, values: structuredClone(user.notificationPreferences), reason: '', verification: '' });
  const openCatalogue = (kind, item) => setDialog({ mode: 'catalogue', target: { ...item, kind }, values: { ...item }, reason: '', verification: '' });
  const openCorrection = record => setDialog({ mode: 'correction', target: record, values: { contact: record.contact || '', internalJobNumber: record.internalJobNumber || '', salesOrderNumber: record.salesOrderNumber || record.planning?.salesOrderNumber || '', customerPoNumber: record.customerPoNumber || '' }, reason: '', verification: '' });
  const openStatus = user => setDialog({ mode: 'status', target: user, values: { status: user.status === 'active' ? 'disabled' : 'active' }, reason: '', verification: '' });

  const showCredential = result => result?.temporaryPassword && setOneTimeCredential({ employee: result.account?.contact || dialog.target?.contact, password: result.temporaryPassword });
  const submitDialog = () => {
    const { mode, target, values, reason, verification } = dialog;
    if (mode === 'employee') return run('employee-create', async () => {
      const result = await administrationActions.createEmployee({ values, reason });
      if (values.profileImage) await administrationActions.uploadEmployeeProfileImage(result.account.id, values.profileImage, { reason });
      return result;
    }, 'Employee account prepared and audited.');
    if (mode === 'customer') return run('customer-create', () => administrationActions.createCustomer({ values, reason }), 'Customer company and authorised contact created and audited.');
    if (mode === 'user') return run(`user-${target.id}`, async () => {
      const changed = ['contact', 'email', 'signInName', 'phone', 'area', 'branchId', 'department'].some(key => String(values[key] || '') !== String(target[key] || ''));
      const result = changed ? await administrationActions.updateAccount(target.id, { values, reason, verification }) : target;
      if (values.profileImage) await administrationActions.uploadEmployeeProfileImage(target.id, values.profileImage, { reason });
      if (!changed && !values.profileImage) throw new Error('Change an account field or choose a profile picture.');
      return result;
    }, 'The account details were updated and audited.');
    if (mode === 'roles') return run(`roles-${target.id}`, () => administrationActions.assignAccountRoles(target.id, { roles: values.roles, reason, verification }), 'The role assignments were updated and audited.');
    if (mode === 'branch') return run(`branch-${target.id}`, () => administrationActions.assignAccountBranch(target.id, { ...values, reason }), 'The branch assignment and impact snapshot were recorded.');
    if (mode === 'reset') return run(`reset-${target.id}`, () => administrationActions.resetUserLogin(target.id, { reason, verification }), 'A temporary login was generated. It is shown once only.', showCredential);
    if (mode === 'profile') return run(`profile-${target.id}`, () => administrationActions.uploadEmployeeProfileImage(target.id, values.profileImage, { reason }), 'The employee profile picture was validated, updated and audited.');
    if (mode === 'archive') return run(`archive-${target.id}`, () => administrationActions.archiveEmployee(target.id, { ...values, reason, verification }), 'The employee was archived without deleting historical ownership.');
    if (mode === 'company') return run(`company-${target.id}`, () => administrationActions.updateCompany(target.id, { values, reason }), 'The customer company was updated and audited.');
    if (mode === 'representative') return run(`rep-${target.id}`, () => administrationActions.assignRepresentative(target.id, { representativeId: values.representativeId, reason }), 'The dedicated representative assignment was updated.');
    if (mode === 'permissions') return run(`permissions-${target.id}`, () => administrationActions.setAccountPermissions(target.id, { permissions: values.permissions, reason, verification }), 'The internal permissions were updated and audited.');
    if (mode === 'notifications') return run(`notifications-${target.id}`, () => administrationActions.updateNotificationPreferences(target.id, { preferences: values, reason }), 'The notification preferences were updated.');
    if (mode === 'catalogue') return run(`catalogue-${target.id}`, () => administrationActions.saveCatalogueItem(target.kind, target.id, { values, reason }), 'The catalogue item was updated and audited.');
    if (mode === 'correction') {
      const allowed = target.workflowType === 'order' ? ['contact', 'internalJobNumber', 'salesOrderNumber', 'customerPoNumber'] : ['contact'];
      const correctionValues = Object.fromEntries(allowed.filter(key => String(values[key] || '').trim() && String(values[key] || '').trim() !== String(target[key] || '').trim()).map(key => [key, values[key]]));
      return run(`correction-${target.id}`, () => administrationActions.correctRecord(target.id, { values: correctionValues, reason, verification, expectedVersion: target.version }), 'The approved correction was appended to the audit history.');
    }
    if (mode === 'status') return run(`status-${target.id}`, () => administrationActions.setAccountStatus(target.id, { status: values.status, reason, verification }), `The account is now ${values.status}.`);
    return undefined;
  };

  const customerUsers = filteredUsers.filter(user => user.category === 'customer');
  const internalUsers = filteredUsers.filter(user => user.category === 'internal');
  const tabs = [['overview', 'Overview'], ['customers', 'Customers'], ['staff', 'User Management'], ['companies', 'Companies'], ['catalogue', 'Catalogue'], ['roles', 'Roles & permissions'], ['records', 'Corrections & archive'], ['configuration', 'Platform setup']];

  return <section className="app-screen operations-desktop administrator-screen" aria-labelledby="administrator-title">
    <header className="operations-hero administrator-hero"><div><span className="eyebrow">{__PUBLIC_PREVIEW__ && serviceMode === 'mock' ? 'Fabricated data · ' : ''}Secure administration</span><h1 id="administrator-title">Platform control.<br /><em>Every change accountable.</em></h1><p>Manage approved customer and employee data through permission-controlled services. Passwords, immutable history and signed records remain protected.</p></div><div className="operations-owner"><span>{account.contact}</span><small>Administrator · Internal desktop</small></div></header>
    {overview && <div className="operations-metrics administrator-metrics"><Metric label="Users" value={overview.summary.users} /><Metric label="Customer companies" value={overview.summary.customerCompanies} /><Metric label="Internal accounts" value={overview.summary.internalAccounts} /><Metric label="Archived records" value={overview.archivedRecords.length} /><Metric label="Audit events" value={overview.summary.auditEvents} /><Metric label="Catalogue products" value={overview.catalogue.products.length} /></div>}
    <nav className="administrator-tabs" aria-label="Administration sections">{tabs.map(([id, label]) => <button key={id} type="button" className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav>
    {(error || message) && <p className={`operations-message ${error ? 'is-error' : ''}`} role={error ? 'alert' : 'status'}>{error || message}</p>}
    {!overview && !error && <div className="operations-empty"><strong>Loading secure administration</strong><p>Preparing the permission-controlled platform overview.</p></div>}

    {overview && tab === 'overview' && <div className="administrator-overview-grid">
      <article className="administrator-panel"><span className="eyebrow">Protected operations</span><h2>Administration</h2><p>Confirmed changes are recorded in the audit history.</p><div className="administrator-action-row"><button className="primary-button" type="button" onClick={onOpenManagement}>Management dashboard</button><button className="secondary-button" type="button" onClick={onOpenAudit}>Audit history</button><button className="secondary-button" type="button" onClick={onOpenArchive}>Archive controls</button></div></article>
      <article className="administrator-panel"><span className="eyebrow">Safety boundaries</span><h2>Administrators cannot</h2><ul><li>View current passwords</li><li>Edit signed certificates or quotation history</li><li>Alter immutable audit events</li><li>Delete active orders</li><li>Override workflow without separate authority</li></ul></article>
      <article className="administrator-panel"><span className="eyebrow">Account lifecycle</span><h2>Secure staff access</h2><p>One identity can hold multiple roles. Username-only staff receive a one-time temporary credential and must change it on first login.</p></article>
      <MockAdministrationControls busy={busy} onRun={run} administrationActions={administrationActions} />
    </div>}

    {overview && ['customers', 'staff'].includes(tab) && <AccountDirectory title={tab === 'customers' ? 'Customer contacts and sign-in identities' : 'Administrator → User Management'} users={tab === 'customers' ? customerUsers : internalUsers} overview={overview} query={query} onQuery={setQuery} filters={filters} onFilters={setFilters} account={account} internal={tab === 'staff'} canEdit={accountCan(account, tab === 'customers' ? PERMISSIONS.MANAGE_CUSTOMER_CONTACTS : PERMISSIONS.MANAGE_INTERNAL_ACCOUNTS)} canPermissions={tab === 'staff' && accountCan(account, PERMISSIONS.MANAGE_ROLES_PERMISSIONS)} canNotifications={accountCan(account, PERMISSIONS.MANAGE_NOTIFICATION_PREFERENCES)} onAdd={tab === 'staff' ? openEmployee : openCustomer} onEdit={openUser} onStatusAction={openStatus} onRoles={openRoles} onBranch={openBranch} onReset={openReset} onArchive={openArchive} onHistory={openHistory} onPermissions={openPermissions} onNotifications={openNotifications} />}

    {overview && tab === 'companies' && <section className="administrator-card-grid">{overview.companies.map(company => <article className="administrator-panel" key={company.id}><span className="eyebrow">{company.area}</span><h2>{company.name}</h2><p>{company.industry} · {company.contacts} authorised contact{company.contacts === 1 ? '' : 's'}</p><dl className="administrator-definition-list"><div><dt>Branch</dt><dd>{overview.branches.find(branch => branch.id === company.branchId)?.name || 'Not assigned'}</dd></div><div><dt>Representative</dt><dd>{overview.representatives.find(rep => rep.id === company.representativeId)?.name || 'Not assigned'}</dd></div></dl>{accountCan(account, PERMISSIONS.MANAGE_CUSTOMER_COMPANIES) && <div className="administrator-action-row"><button className="secondary-button" type="button" onClick={() => openCompany(company)}>Edit company</button><button className="text-button" type="button" onClick={() => openRepresentative(company)}>Assign representative</button></div>}</article>)}</section>}
    {overview && tab === 'catalogue' && <section className="administrator-catalogue-grid"><div className="administrator-panel"><span className="eyebrow">Product categories</span><h2>Approved navigation</h2>{overview.catalogue.categories.map(item => <AdminListRow key={item.id} title={item.name} detail={`${item.number} · ${humanise(item.status)}`} onEdit={accountCan(account, PERMISSIONS.MANAGE_PRODUCTS) ? () => openCatalogue('category', item) : null} />)}</div><div className="administrator-panel"><span className="eyebrow">Product catalogue</span><h2>Customer-visible information</h2>{overview.catalogue.products.slice(0, 60).map(item => <AdminListRow key={item.id} title={`${item.code} · ${item.name}`} detail={`${humanise(item.category)} · ${humanise(item.status)}`} onEdit={accountCan(account, PERMISSIONS.MANAGE_PRODUCTS) ? () => openCatalogue('product', item) : null} />)}</div></section>}
    {overview && tab === 'roles' && <section className="administrator-card-grid role-permission-grid">{overview.roles.filter(role => role.id !== USER_ROLES.CUSTOMER).map(role => <article className="administrator-panel" key={role.id}><span className="eyebrow">{role.permissions.length} default permissions</span><h2>{role.label}</h2><div className="administrator-token-list">{role.permissions.map(permission => <span key={permission}>{humanise(permission)}</span>)}</div></article>)}</section>}
    {overview && tab === 'records' && <div className="administrator-catalogue-grid"><section className="administrator-panel"><span className="eyebrow">Approved corrections only</span><h2>RFQ and order references</h2><p>Corrections create new audit evidence. Workflow status, signed certificates, quotation versions and historical events are blocked.</p>{overview.correctionRecords.slice(0, 80).map(record => <AdminListRow key={record.id} title={`${record.reference} · ${record.company}`} detail={`${humanise(record.workflowType)} · ${humanise(record.trackingStatus)}`} onEdit={accountCan(account, PERMISSIONS.CORRECT_APPROVED_RECORDS) ? () => openCorrection(record) : null} />)}</section><section className="administrator-panel"><span className="eyebrow">Retention controls</span><h2>{overview.archivedRecords.length} archived records</h2><button className="primary-button" type="button" onClick={onOpenArchive}>Open archive management</button></section></div>}
    {overview && tab === 'configuration' && <section className="administrator-card-grid">{Object.entries(overview.configurations).map(([department, configuration]) => <article className="administrator-panel" key={department}><span className="eyebrow">Approved options</span><h2>{humanise(department)}</h2>{Object.entries(configuration).map(([key, values]) => <div className="administrator-config-row" key={key}><strong>{humanise(key)}</strong><span>{values.map(humanise).join(' · ')}</span></div>)}</article>)}<article className="administrator-panel"><span className="eyebrow">Branch directory</span><h2>Production locations</h2>{overview.branches.map(branch => <div className="administrator-config-row" key={branch.id}><strong>{branch.name}</strong><span>{branch.role}</span></div>)}</article></section>}

    {dialog.mode && createPortal(<AdministrationDialog dialog={dialog} onChange={setDialog} overview={overview} users={internalUsers} busy={busy} onCancel={() => setDialog(emptyDialog())} onSubmit={submitDialog} />, document.body)}
    {oneTimeCredential && createPortal(<OneTimeCredential value={oneTimeCredential} onClose={() => setOneTimeCredential(null)} />, document.body)}
  </section>;
}

function AccountDirectory({ title, users, overview, query, onQuery, filters, onFilters, account, internal, canEdit, canPermissions, canNotifications, onAdd, onEdit, onStatusAction, onRoles, onBranch, onReset, onArchive, onHistory, onPermissions, onNotifications }) {
  const setFilter = (key, value) => onFilters(current => ({ ...current, [key]: value }));
  return <section className="administrator-panel">
    <div className="operations-section-title"><div><span className="eyebrow">Separated identity realm</span><h2>{title}</h2></div><div className="administrator-action-row"><small>{users.length} matching</small>{canEdit && <button className="primary-button" type="button" onClick={onAdd}>{internal ? 'Add Employee' : 'Add Customer'}</button>}</div></div>
    <div className="administrator-filter-row"><label className="administrator-search"><span>Search directory</span><input value={query} onChange={event => onQuery(event.target.value)} placeholder="Name, email or username…" /></label><SelectField label="Status" value={filters.status} options={[{ value: 'all', label: 'All statuses' }, ...overview.accountStatuses.map(value => ({ value, label: humanise(value) }))]} onChange={value => setFilter('status', value)} />{internal && <><SelectField label="Branch" value={filters.branch} options={[{ value: 'all', label: 'All branches' }, ...overview.branches.map(item => ({ value: item.id, label: item.name }))]} onChange={value => setFilter('branch', value)} /><SelectField label="Department" value={filters.department} options={[{ value: 'all', label: 'All departments' }, ...overview.departments.map(value => ({ value, label: value }))]} onChange={value => setFilter('department', value)} /><SelectField label="Role" value={filters.role} options={[{ value: 'all', label: 'All roles' }, ...overview.roles.filter(item => item.id !== USER_ROLES.CUSTOMER).map(item => ({ value: item.id, label: item.label }))]} onChange={value => setFilter('role', value)} /></>}</div>
    <div className="administrator-table-wrap"><table className="administrator-table"><thead><tr><th>User</th><th>Branch / department</th><th>Role(s)</th><th>Last login</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><div className="administrator-user-cell">{user.profileImageUrl ? <img src={user.profileImageUrl} alt="" /> : <span>{user.contact?.[0] || '?'}</span>}<div><strong>{user.contact}</strong><small>{user.email || user.signInName || 'No login identifier'}</small></div></div></td><td>{overview.branches.find(item => item.id === user.branchId)?.name || user.company}<small>{user.department || user.area}</small></td><td><div className="administrator-token-list compact">{(user.roles || [user.role]).map(role => <span key={role}>{humanise(role)}</span>)}</div></td><td>{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString() : 'Never'}<small>{user.loginHistoryCount || 0} recorded attempt(s)</small></td><td><StatusBadge status={user.status} label={humanise(user.status)} className="status-pill" /></td><td><div className="administrator-row-actions">{canEdit && <button className="text-button" type="button" onClick={() => onEdit(user)}>Edit</button>}{internal && canPermissions && user.id !== account.id && <button className="text-button" type="button" onClick={() => onRoles(user)}>Roles</button>}{internal && canEdit && <button className="text-button" type="button" onClick={() => onBranch(user)}>Branch</button>}{canEdit && user.id !== account.id && <button className="text-button" type="button" onClick={() => onReset(user)}>Reset login</button>}{canNotifications && <button className="text-button" type="button" onClick={() => onNotifications(user)}>Notifications</button>}{internal && <button className="text-button" type="button" onClick={() => onHistory(user)}>History</button>}{canPermissions && user.id !== account.id && <button className="text-button" type="button" onClick={() => onPermissions(user)}>Permissions</button>}{canEdit && user.id !== account.id && user.status !== 'archived' && <button className="text-button" type="button" onClick={() => onStatusAction(user)}>{user.status === 'active' ? 'Disable' : 'Activate'}</button>}{internal && canEdit && user.id !== account.id && user.status !== 'archived' && <button className="text-button danger-text" type="button" onClick={() => onArchive(user)}>Archive</button>}</div></td></tr>)}</tbody></table></div>
    {!users.length && <div className="operations-empty"><strong>No matching users</strong><p>{internal ? 'Change the directory search or filters.' : 'No customer accounts exist yet. Add the first authorised customer when internal testing begins.'}</p></div>}
  </section>;
}

function AdministrationDialog({ dialog, onChange, overview, users, busy, onCancel, onSubmit }) {
  const setValue = (key, value) => onChange(current => ({ ...current, values: { ...current.values, [key]: value } }));
  const set = (key, value) => onChange(current => ({ ...current, [key]: value }));
  const highRisk = ['roles', 'permissions', 'correction', 'reset', 'archive'].includes(dialog.mode) || dialog.mode === 'status' && ['disabled', 'suspended', 'archived'].includes(dialog.values.status);
  const titles = { employee: 'Add Employee', customer: 'Add Customer Account', user: dialog.target?.category === 'customer' ? 'Edit customer account' : 'Edit employee account', roles: 'Assign multiple roles', branch: 'Change branch assignment', reset: 'Generate temporary password', archive: 'Archive Employee', history: 'User audit and login history', company: 'Edit customer company', representative: 'Assign dedicated representative', permissions: 'Change account permissions', notifications: 'Change notification preferences', catalogue: 'Edit catalogue information', correction: 'Record approved correction', status: `${humanise(dialog.values.status)} account` };
  if (dialog.mode === 'history') return <DialogShell title={titles.history} onCancel={onCancel}><HistoryPanel values={dialog.values} /></DialogShell>;
  return <DialogShell title={titles[dialog.mode]} onCancel={onCancel}><p>Confirm the change carefully. Previous and new values are recorded in the audit history.</p>
    {dialog.mode === 'employee' && <><EmployeeForm values={dialog.values} setValue={setValue} overview={overview} /><ProfileImageField file={dialog.values.profileImage} onChange={file => setValue('profileImage', file)} /></>}
    {dialog.mode === 'customer' && <div className="administrator-form-grid"><Field label="Company name" value={dialog.values.companyName} onChange={value => setValue('companyName', value)} /><Field label="Authorised contact" value={dialog.values.contactName} onChange={value => setValue('contactName', value)} /><Field label="Email address" type="email" value={dialog.values.email} onChange={value => setValue('email', value)} /><Field label="Telephone" value={dialog.values.phone} onChange={value => setValue('phone', value)} /><SelectField label="Area" value={dialog.values.area} options={overview.areas} onChange={value => setValue('area', value)} /><Field label="Industry" value={dialog.values.industry} onChange={value => setValue('industry', value)} /><SelectField label="Branch" value={dialog.values.branchId} options={overview.branches.map(item => ({ value: item.id, label: item.name }))} onChange={value => setValue('branchId', value)} /><SelectField label="Dedicated representative" value={dialog.values.representativeId} options={overview.representatives.map(item => ({ value: item.id, label: `${item.name} · ${item.branch}` }))} onChange={value => setValue('representativeId', value)} /><Field label="Temporary password" type="password" value={dialog.values.password} onChange={value => setValue('password', value)} /></div>}
    {dialog.mode === 'user' && <div className="administrator-form-grid"><Field label="Full name" value={dialog.values.contact} onChange={value => setValue('contact', value)} /><Field label="Email address (optional when username exists)" type="email" value={dialog.values.email} onChange={value => setValue('email', value)} /><Field label="Username" value={dialog.values.signInName} onChange={value => setValue('signInName', value)} /><Field label="Phone number" value={dialog.values.phone} onChange={value => setValue('phone', value)} /><SelectField label="Department" value={dialog.values.department} options={overview.departments} onChange={value => setValue('department', value)} /></div>}
    {dialog.mode === 'user' && dialog.target.category === 'internal' && <ProfileImageField file={dialog.values.profileImage} onChange={file => setValue('profileImage', file)} />}
    {dialog.mode === 'roles' && <><p className="administrator-risk-note">Removing a role can immediately remove access to active work. Review responsibilities before confirming.</p><CheckList values={dialog.values.roles} options={overview.roles.filter(item => item.id !== USER_ROLES.CUSTOMER)} onChange={roles => setValue('roles', roles)} /></>}
    {dialog.mode === 'branch' && <div className="administrator-form-grid"><SelectField label="New branch" value={dialog.values.branchId} options={overview.branches.map(item => ({ value: item.id, label: item.name }))} onChange={value => setValue('branchId', value)} /><Field label="Effective date" type="date" value={dialog.values.effectiveDate} onChange={value => setValue('effectiveDate', value)} /></div>}
    {dialog.mode === 'reset' && <p className="administrator-risk-note">The existing credential will be invalidated. The replacement temporary password is displayed once and the account holder must change it at first login.</p>}
    {dialog.mode === 'archive' && <div className="administrator-form-grid"><Field label="Last working date" type="date" value={dialog.values.lastWorkingDate} onChange={value => setValue('lastWorkingDate', value)} /><SelectField label="Replacement employee (required when active work exists)" value={dialog.values.replacementEmployeeId} options={users.filter(user => user.id !== dialog.target.id && user.status === 'active').map(user => ({ value: user.id, label: user.contact }))} onChange={value => setValue('replacementEmployeeId', value)} /></div>}
    {dialog.mode === 'company' && <div className="administrator-form-grid"><Field label="Company name" value={dialog.values.name} onChange={value => setValue('name', value)} /><SelectField label="Area" value={dialog.values.area} options={overview.areas} onChange={value => setValue('area', value)} /><Field label="Industry" value={dialog.values.industry} onChange={value => setValue('industry', value)} /><SelectField label="Branch" value={dialog.values.branchId} options={overview.branches.map(item => ({ value: item.id, label: item.name }))} onChange={value => setValue('branchId', value)} /></div>}
    {dialog.mode === 'representative' && <SelectField label="Dedicated sales representative" value={dialog.values.representativeId} options={overview.representatives.map(item => ({ value: item.id, label: `${item.name} · ${item.branch}` }))} onChange={value => setValue('representativeId', value)} />}
    {dialog.mode === 'permissions' && <CheckList values={dialog.values.permissions} options={Object.values(PERMISSIONS).map(value => ({ id: value, label: humanise(value) }))} onChange={permissions => setValue('permissions', permissions)} />}
    {dialog.mode === 'notifications' && <div className="administrator-form-grid">{['inApp', 'email', 'push'].map(channel => <label className="administrator-check" key={channel}><input type="checkbox" checked={dialog.values.channels[channel]} disabled={channel === 'inApp'} onChange={event => setValue('channels', { ...dialog.values.channels, [channel]: event.target.checked })} /><span>{humanise(channel)}</span></label>)}</div>}
    {dialog.mode === 'catalogue' && <div className="administrator-form-grid"><Field label={dialog.target.kind === 'product' ? 'Product name' : 'Category name'} value={dialog.values.name} onChange={value => setValue('name', value)} />{dialog.target.kind === 'product' && <><Field label="Product code" value={dialog.values.code} onChange={value => setValue('code', value)} /><SelectField label="Category" value={dialog.values.category} options={overview.catalogue.categories.map(item => ({ value: item.id, label: item.name }))} onChange={value => setValue('category', value)} /></>}<Field label="Description" value={dialog.values.description} onChange={value => setValue('description', value)} /><SelectField label="Status" value={dialog.values.status} options={[{ value: 'active', label: 'Active' }, { value: 'inactive', label: 'Inactive' }]} onChange={value => setValue('status', value)} /></div>}
    {dialog.mode === 'correction' && <>{!!dialog.target.items?.length && <div className="configured-unit-list"><h3>Unit details</h3>{dialog.target.items.map(item => <ConfiguredUnitDetails key={item.lineId || item.id || `${item.productId}-${item.code}`} unit={item} context="Administration" />)}</div>}<div className="administrator-form-grid"><Field label="Contact person" value={dialog.values.contact} onChange={value => setValue('contact', value)} />{dialog.target.workflowType === 'order' && <><Field label="Internal job number" value={dialog.values.internalJobNumber} onChange={value => setValue('internalJobNumber', value)} /><Field label="Sales Order Number" value={dialog.values.salesOrderNumber} onChange={value => setValue('salesOrderNumber', value)} /><Field label="Customer PO number" value={dialog.values.customerPoNumber} onChange={value => setValue('customerPoNumber', value)} /></>}</div></>}
    {dialog.mode === 'status' && <p className="administrator-risk-note">You are about to set <strong>{dialog.target.contact}</strong> to <strong>{humanise(dialog.values.status)}</strong>.</p>}
    <label><span>Reason for change</span><textarea value={dialog.reason} onChange={event => set('reason', event.target.value)} placeholder="Explain why this approved change is required…" /></label>{highRisk && <Field label="Current administrator password" type="password" value={dialog.verification} onChange={value => set('verification', value)} />}
    <div className="administrator-action-row"><button type="button" className="primary-button" disabled={Boolean(busy) || dialog.reason.trim().length < 8 || highRisk && !dialog.verification} onClick={onSubmit}>{busy ? 'Saving…' : 'Confirm and record change'}</button><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button></div>
  </DialogShell>;
}

function EmployeeForm({ values, setValue, overview }) {
  const toggleRole = role => setValue('additionalRoles', values.additionalRoles.includes(role) ? values.additionalRoles.filter(item => item !== role) : [...values.additionalRoles, role]);
  return <><div className="administrator-form-grid"><Field label="First name" value={values.firstName} onChange={value => { setValue('firstName', value); if (!values.displayName) setValue('displayName', `${value} ${values.surname}`.trim()); }} /><Field label="Surname" value={values.surname} onChange={value => setValue('surname', value)} /><Field label="Display name" value={values.displayName} onChange={value => setValue('displayName', value)} /><Field label="Work email (optional)" type="email" value={values.email} onChange={value => { setValue('email', value); if (value && values.activationMethod === 'administrator_temporary_password') setValue('activationMethod', 'verified_email_invitation'); }} /><Field label="Username (required)" value={values.username} onChange={value => { setValue('username', value); if (!values.email) setValue('activationMethod', 'administrator_temporary_password'); }} /><Field label="Temporary password" type="password" value={values.password} onChange={value => setValue('password', value)} /><SelectField label="Branch" value={values.branchId} options={overview.branches.map(item => ({ value: item.id, label: item.name }))} onChange={value => setValue('branchId', value)} /><SelectField label="Department" value={values.department} options={overview.departments} onChange={value => setValue('department', value)} /><SelectField label="Primary role" value={values.primaryRole} options={overview.roles.filter(item => item.id !== USER_ROLES.CUSTOMER).map(item => ({ value: item.id, label: item.label }))} onChange={value => setValue('primaryRole', value)} /><SelectField label="Authentication type" value={values.authenticationType} options={overview.authenticationTypes.map(value => ({ value, label: humanise(value) }))} onChange={value => setValue('authenticationType', value)} /><SelectField label="Activation method" value={values.activationMethod} options={overview.activationMethods.map(value => ({ value, label: humanise(value) }))} onChange={value => setValue('activationMethod', value)} /></div><fieldset className="administrator-role-picker"><legend>Additional roles</legend>{overview.roles.filter(item => item.id !== USER_ROLES.CUSTOMER && item.id !== values.primaryRole).map(role => <label key={role.id}><input type="checkbox" checked={values.additionalRoles.includes(role.id)} onChange={() => toggleRole(role.id)} /><span>{role.label}</span></label>)}</fieldset></>;
}

function HistoryPanel({ values }) { return <div className="administrator-history-grid"><section><h3>Immutable user audit</h3>{values.audit.length ? values.audit.map(event => <AdminListRow key={event.id} title={humanise(event.eventType)} detail={`${new Date(event.timestamp).toLocaleString()} · ${event.actingUser.displayName}`} />) : <p>No user changes recorded.</p>}</section><section><h3>Login history</h3>{values.logins.length ? values.logins.map(event => <AdminListRow key={event.id} title={humanise(event.outcome)} detail={`${new Date(event.occurredAt).toLocaleString()} · ${humanise(event.reason || 'verified')}`} />) : <p>No login attempts recorded.</p>}</section></div>; }
function OneTimeCredential({ value, onClose }) { return <DialogShell title="Temporary password · display once" onCancel={onClose}><p>Securely provide this temporary password to <strong>{value.employee}</strong>. It will not appear in audit history or the directory again.</p><output className="administrator-one-time-password">{value.password}</output><p className="administrator-risk-note">The account holder must replace it immediately at first login.</p><button className="primary-button" type="button" onClick={onClose}>I have stored it securely</button></DialogShell>; }
function DialogShell({ title, onCancel, children }) { return <div className="administrator-dialog-backdrop" role="presentation"><section className="administrator-dialog" role="dialog" aria-modal="true" aria-labelledby="administrator-dialog-title"><div className="operations-section-title"><div><span className="eyebrow">Confirmation required</span><h2 id="administrator-dialog-title">{title}</h2></div><button type="button" className="text-button" onClick={onCancel}>Close</button></div>{children}</section></div>; }
function CheckList({ values, options, onChange }) { return <div className="administrator-permission-editor">{options.map(option => { const id = option.id || option.value; return <label key={id}><input type="checkbox" checked={values.includes(id)} onChange={event => onChange(event.target.checked ? [...values, id] : values.filter(item => item !== id))} /><span>{option.label || humanise(id)}</span></label>; })}</div>; }
function ProfileImageField({ file, onChange }) { return <label className="settings-field"><span>Profile picture</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => onChange(event.target.files?.[0] || null)} /><small>{file ? `${file.name} · ${Math.ceil(file.size / 1024)} KB` : 'Optional JPG, PNG or WebP · maximum 2 MB'}</small></label>; }
function Field({ label, value, onChange, type = 'text' }) { return <label><span>{label}</span><input type={type} value={value || ''} onChange={event => onChange(event.target.value)} /></label>; }
function SelectField({ label, value, options, onChange }) { const normalised = options.map(item => typeof item === 'string' ? { value: item, label: item } : item); return <label><span>{label}</span><select value={value || ''} onChange={event => onChange(event.target.value)}>{!normalised.some(item => item.value === '') && !['all'].includes(value) && <option value="">Choose…</option>}{normalised.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>; }
function AdminListRow({ title, detail, onEdit }) { return <div className="administrator-list-row"><div><strong>{title}</strong><small>{detail}</small></div>{onEdit && <button type="button" className="text-button" onClick={onEdit}>Edit</button>}</div>; }
function Metric({ label, value }) { return <article><strong>{value ?? 0}</strong><span>{label}</span></article>; }
