export const PUBLIC_CATALOGUE_PDFS = Object.freeze([
  Object.freeze({ path: 'assets/datasheets/PBB-product-sheet.pdf', purpose: 'Customer-facing PBB product information' }),
  Object.freeze({ path: 'assets/datasheets/Pressure-gauge-ordering-guide.pdf', purpose: 'Customer-facing pressure gauge selection guidance' }),
  Object.freeze({ path: 'assets/datasheets/RPT106-product-sheet.pdf', purpose: 'Customer-facing RPT106 product information' }),
  Object.freeze({ path: 'assets/datasheets/Temperature-ordering-guide.pdf', purpose: 'Customer-facing temperature instrument selection guidance' }),
  Object.freeze({ path: 'assets/datasheets/Utility-gauge-overview.pdf', purpose: 'Customer-facing utility gauge product overview' }),
]);

const BRAND_AND_CATEGORY_ASSETS = [
  'assets/images/calibration.png',
  'assets/images/diaphragm-gauge.png',
  'assets/images/favicon.ico',
  'assets/images/gas-analysis.png',
  'assets/images/process-gauge.png',
  'assets/images/rhomberg-connect-icon-192.png',
  'assets/images/rhomberg-connect-icon-512.png',
  'assets/images/rhomberg-connect-logo-compact.png',
  'assets/images/rhomberg-connect-logo-full-dark.png',
  'assets/images/rhomberg-connect-logo-loading.png',
  'assets/images/rhomberg-connect-logo-splash.png',
  'assets/images/rhomberg-connect-symbol.png',
  'assets/images/rhomberg-gauge-mark.svg',
  'assets/images/rhomberg-wordmark-transparent.png',
  'assets/images/switches.png',
  'assets/images/temperature-sensors.png',
  'assets/images/temperature.png',
  'assets/images/transmitters.png',
  'assets/images/utility-gauge.png',
];

const PRODUCT_ASSETS = [
  'amt.webp',
  'analysis-family.webp',
  'atlas-900.webp',
  'bbr.webp',
  'cbc.webp',
  'comparator.webp',
  'dbb.webp',
  'dpg-s281.webp',
  'electrical-contacts.webp',
  'heat-reducer.webp',
  'hgz.webp',
  'oxytrend.webp',
  'p8863-pm.webp',
  'p8863.webp',
  'pbb.webp',
  'pbg.webp',
  'pbj.webp',
  'pbk.webp',
  'pbn.webp',
  'pbr.webp',
  'pbs.webp',
  'pbu.webp',
  'pbx.webp',
  'pbz.webp',
  'pcb.webp',
  'pdbh.webp',
  'rbt100.webp',
  'rbt102.webp',
  'rbt103.webp',
  'rbt30h.webp',
  'rbt30s.webp',
  'rdpg10.webp',
  'rpt-series.webp',
  'rpt102.webp',
  'rpt103.webp',
  'rpt106.webp',
  'rpt161.webp',
  'rpt200-level.webp',
  'rpt400-401.webp',
  'rtb118.webp',
  'rtd-pt100.webp',
  'sadmini2.webp',
  'seal-dairy.webp',
  'seal-family.webp',
  'seal-flanged.webp',
  'seal-mini.webp',
  'seal-pulp-paper.webp',
  'seal-triclamp.webp',
  'seal-xwd4.webp',
  'seal-xwd7.webp',
  'snubber.webp',
  'sps103.webp',
  'switch-family.webp',
  'thermocouple.webp',
  'tpb.webp',
  'tps.webp',
  'uec-100-series.webp',
  'uec-12-series.webp',
  'uec-one-series.webp',
  'v-line.webp',
  'vibration-free-movement.webp',
  'well-flanged.webp',
  'well-straight.webp',
  'well-tapered.webp',
  'zirconia-6801.webp',
].map(name => `assets/images/products/${name}`);

export const PRODUCTION_ASSETS = Object.freeze([
  ...PUBLIC_CATALOGUE_PDFS.map(item => item.path),
  ...BRAND_AND_CATEGORY_ASSETS,
  ...PRODUCT_ASSETS,
].sort());

export const PRODUCTION_ROOT_FILES = Object.freeze([
  'app.js',
  'index.html',
  'manifest.webmanifest',
  'runtime-config.js',
  'styles.css',
  'sw.js',
  'web.config',
]);

export const PRODUCTION_PRECACHE_FILES = Object.freeze([
  './',
  './index.html',
  './styles.css',
  './runtime-config.js',
  './app.js',
  './manifest.webmanifest',
  './assets/images/rhomberg-connect-logo-full-dark.png',
  './assets/images/rhomberg-connect-logo-compact.png',
  './assets/images/rhomberg-connect-logo-splash.png',
  './assets/images/rhomberg-connect-logo-loading.png',
  './assets/images/rhomberg-connect-symbol.png',
  './assets/images/rhomberg-connect-icon-192.png',
  './assets/images/rhomberg-connect-icon-512.png',
  './assets/images/rhomberg-gauge-mark.svg',
  './assets/images/rhomberg-wordmark-transparent.png',
]);
